ingress:
  namespace: garbidz-staging

image:
  tag: pr-56


resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 500Mi

db_url: jdbc:mysql://garbidz-mysql.garbidz-staging:3306/garbidz
