
ingress:
  namespace: garbidz-staging

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 500Mi

db_url: jdbc:mysql://garbidz-mysql.garbidz-staging:3306/garbidz
db_user: garbidzuser
db_password: garbidzpw
