apiVersion: apps/v1
kind: Deployment
metadata:
  name: garbidz-deployment
  labels:
    app: garbidz-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  selector:
    matchLabels:
      app: garbidz-deployment
  template:
    metadata:
      labels:
        app: garbidz-deployment
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "java" ]
          args: ["-javaagent:opentelemetry-javaagent.jar", "-jar", "app.jar"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: debug
              containerPort: 5005
              protocol: TCP
            - name: jmx
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: http
            failureThreshold: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 10
          resources: 
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Dcom.sun.management.jmxremote
                -Dcom.sun.management.jmxremote.authenticate=false
                -Dcom.sun.management.jmxremote.ssl=false
                -Dcom.sun.management.jmxremote.local.only=false
                -Dcom.sun.management.jmxremote.port=5000
                -Dcom.sun.management.jmxremote.rmi.port=5000
                -Djava.rmi.server.hostname=127.0.0.1
                -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
            # https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/#otel_exporter_otlp_traces_endpoint
            # https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.monitoring:4317
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=garbidz"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: DB_URL
              value: {{.Values.db_url}}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: garbidz-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: garbidz-secret
