apiVersion: apps/v1
kind: Deployment
metadata:
  name: garbidz-deployment
  labels:
    app: garbidz-deployment
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  selector:
    matchLabels:
      app: garbidz-deployment
  template:
    metadata:
      labels:
        app: garbidz-deployment
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources: 
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_URL
              value: {{.Values.db_url}}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: garbidz-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: garbidz-secret
