kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: garbidz
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/auth-signin: 'https://$host/oauth2/start?rd=$escaped_request_uri'
#    nginx.ingress.kubernetes.io/auth-url: 'https://$host/oauth2/auth'
#    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
#    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
#    ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
    - hosts:
        - garbidz.adamzverka.com
      secretName: garbidz-prod-cert
  rules:
    - host: garbidz.adamzverka.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garbidz-deployment
                port:
                  number: 8080
