kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: garbidz
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - garbidz.adamzverka.com
      secretName: garbidz-staging-cert
  rules:
    - host: garbidz.adamzverka.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: garbidz-deployment
                port:
                  number: 8080
