---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: garbidz-staging
spec:
  encryptedData:
    mysql-password: AgCvryoAzR3qqs7CSnua0ZwpbmY4BGoqM/1QXSxWcgXCsPrJOaGsE9b/hn0uDUeWKAzUI3Im7KRTkwCdlG8O5uiEUJguFoVUT3QlgolahMBK0xRw78RRcb6jLTgImaC2O9C41ZidGV9Xq4R6qItbRkAYADBplPGuWWfsbyEECmnXY6tsGkX2mFCPLKs+6/kMbSj+dT3i9c0P2c07giJc0PipsL3hp5OljDpz4uzu1XZTupp6VV9yASPa5on3ZTOoGID+DK95j7hpyRnveLcyD1Is7Kp4p/kajaPBb2vewKSG+SastFpYiCmy3Q3+S9q40UbhDvM3cCJa8V4rA7/lSNcAMEtpTYEZQ6x0riRjLn6VyT3BnMaUC6rUvTy8mFPeIww941/oyLwC7fo+6hK8W1V6n2sveBJ1wUgeWEmIjaWmuLn3IdqBDFMYn3n+vrVubeg4m/ufvFAmp1CwibIR2UE6Lg2i9dAkkiNyno3TuDK46I3nirej540IMDPZA0j3JdAvq/Kaq/VdJfwtQbRnzGjR6DGYiqevAjDggPVtq6kyFp0dzvOuI54+giXAAn/q7diVGOw9HOs8puxI0K/5/pxHh3BeBjcBkNfkvybqQoeueMHkb6O3jLI8gLuuHjJVVonafPg0UIswZ/sN78n5qaHUiuc+reV8/DRJrrEPrMRxh4Ej2SdHyKn7eYP6j53PyHZ8zNULU7cd/n135pqG
    mysql-root-password: AgCin7XEgVX06j1IcenJItfD3g8Ozyn6Vs/yfCsy6eEbK8mO3SqeU7dGErzR2vsvN80B1u1WdkhSWoI5TKhuEc9pTaomS4Qd9EZNPgQs1pvSESMNvsQCCtjWUl8d3OIVOuz6fm85ywqltv6wq6mMycr1sKIA91vTHPxem6ManlZB8ec2MQbmQhY/XfGcNRAkypgmMakB1o7wUMtU3yjLuDJyAaOCznhlmH4yc6YTcDFzrb9sNPbtbZ/EZTc8pmTQsK1qSoLcBL3EJBFhvgDkwbM1VNj8sPkCoA/4dSjONMB5UeyRYsr9LWM6OrjQy5pZ1N6x7bc8CuV2omSbG5w6PVCS8c8GGhid1G7NeWNrQEIThNZBi2qQMjoZBvOaVWCSh2ZvC4VkiPEB981LCkfdeSxVVYvhb3Qa7aGbQOUAJO5P/yG0ydWCz1pQydjRy1glAOwdy/vc5EEWj3FZ9XstF449mmuWQpgDrmu4rZPx/7DLEhrwa5OQriH/sNex9dOG/VsJtUPdfs76YepDAmTXTqwYnOOQeSCHn2Pn/+i4aMcZD0g5kSqfKXw/FP18/+a6TLUOaiqcwAgbVzBq1px+ct7ig9OdZ18b/QinEF12F0QD+CyMB54E6q8hOVhaqhPyJpsvk9aaWAOKn7tCHKy5XYbzghuLbthLjcM8S7l3Hend5xH/THRPDQ53DXaK3ov0XS8j0yw4MXxSYYNO6qz8ckgRnQKjGsKtXUaBP1E1zD8=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: garbidz-staging
    type: Opaque
