mysql:
  # Primary database configuration
  primary:
    # Enable persistence using Persistent Volume Claims
    persistence:
      # If true, use a Persistent Volume Claim, If false, use emptyDir
      enabled: true
      size: 1Gi
    # MySQL primary Pod security context
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    # MySQL primary container security context
    containerSecurityContext:
      enabled: true
      runAsUser: 1001

  # Secondary database configuration
  secondary:
    # Enable persistence using Persistent Volume Claims
    persistence:
      # If true, use a Persistent Volume Claim, If false, use emptyDir
      enabled: false
    # MySQL secondary Pod security context
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    # MySQL secondary container security context
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
