---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garbidz-staging
  namespace: argocd
spec:
  project: garbidz-staging
  source:
    repoURL: https://github.com/adamzv/garbidz-gitops.git
    targetRevision: main
    path: garbidz
    helm:
      valueFiles:
      - ../envs/staging/garbidz/values.yaml
      parameters:
        - name: "replicaCount"
          value: "1"
        - name: "image.tag"
          value: main
  destination:
    server: https://kubernetes.default.svc
    namespace: garbidz-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true