---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: garbidz-staging
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      chart: mysql
      targetRevision: 9.10.1
      helm:
        valueFiles:
        - $values/envs/staging/mysql/values.yaml
    - repoURL: https://github.com/adamzv/garbidz-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: garbidz-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true