---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: garbidz-staging
  source:
    repoURL: https://github.com/adamzv/garbidz-gitops.git
    targetRevision: main
    path: mysql
    helm:
      valueFiles:
        - ../envs/staging/mysql/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: garbidz-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true