---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: garbidz-staging
  sources:
    - chart: mysql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 9.10.1
      helm:
        version: v3
        releaseName: mysql
    - repoURL: https://github.com/adamzv/garbidz-gitops.git
      targetRevision: main
      path: garbidz
      helm:
        valueFiles:
          - ../envs/staging/mysql/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: garbidz-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true