apiVersion: v1
kind: Service
metadata:
  name: spring-kafka-deployment
  labels:
    app: spring-kafka-deployment
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: spring-kafka-deployment
